In [ ]:
"""1. Sayılardan oluşan bir boyutlu array oluşturulur.
Arrayi oluştururken sayıların veri tipini integer olarak belirtilir.
Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.

2.İki ve üç boyutlu arrayler oluşturulur.
Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır.
Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

3.Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur.
Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır

4.Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur.
Bu arrayler satır ve sütun bazında birleştirilir. """

'1. Sayılardan oluşan bir boyutlu array oluşturulur.\nArrayi oluştururken sayıların veri tipini integer olarak belirtilir.\nOluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.\n\n2.İki ve üç boyutlu arrayler oluşturulur.\nBu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır.\nArrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.\n\n3.Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur.\nArrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır\n\n4.Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur.\nBu arrayler satır ve sütun bazında birleştirilir. '

In [ ]:
"""1. Sayılardan oluşan bir boyutlu array oluşturulur.
Arrayi oluştururken sayıların veri tipini integer olarak belirtilir.
Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. """

array1 =  ([1,2,3,4,5,]) #1 boyutlu
eleman_sayisi1= len(array1)
print (eleman_sayisi1)

# Dizi boyutu .ndim ile kontrol edilebilir numpy kütüphanesi ile
boyut1 = 1
print("Dizinin boyutu:", boyut1)

#array1 = np.array ([1,2,3,4,5,]) #1 boyutlu
#eleman_sayisi1= len(array1)
#print (eleman_sayisi1)

# Dizi boyutu .ndim ile kontrol edilebilir numpy kütüphanesi ile
#boyut1 = array1.ndim
#print("Dizinin boyutu:", boyut1)"""

5
Dizinin boyutu: 1


In [ ]:
"""2.İki ve üç boyutlu arrayler oluşturulur.
Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır.
Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. """

array2 = [
    [1,2,3],
    [4,5,6]
    ] # 2 boyutlu dizi
print (array2)

print()
print()
array3 = [
    [[10,20]],
    [[30,40]],
    [[50,60]]] #3 boyutlu
print(array3)



[[1, 2, 3], [4, 5, 6]]


[[[10, 20]], [[30, 40]], [[50, 60]]]


In [ ]:
# dizilerin boyutu
array2_boyut = len(array2)
array3_boyut = len(array3)
print(array2_boyut)
print(array3_boyut)



2
3


In [ ]:
#eleman sayıları
eleman_sayisi2 = sum(len(row) for row in array2) # satırlardaki elemanları saydırdı
print("array2 toplam eleman sayısı:", eleman_sayisi2)

eleman_sayisi3 = sum(len(row) for row in array2)
print("array2 toplam eleman sayısı:", eleman_sayisi3)


array2 toplam eleman sayısı: 6
array2 toplam eleman sayısı: 6


In [ ]:
# satır sütun bilgileri
# len komutu 1 boyutluda direkt eleman sayısını verir
#çok boyutlularda da satır sayısnı verir
# len ile satır sayısı alınabilir
# ve sıfırıncı indisten herhangi sütun sayısı hesaplanabilir

satir2 = len(array2)
print("array2'nin satır sayısı:", satir2)
print()
sutun2= len(array2[0]) # direkt ilk indexten alınır
print("array2'nin sütun sayısı:", sutun2)
print()

satir3 =len(array3)
print("array3'ün satır sayısı:", satir3)
print()
sutun3 = len(array3[0][0]) # ilk indexin ilk indexinden alınır
print("array2'ün sütun sayısı:", sutun3)



array2'nin satır sayısı: 2

array2'nin sütun sayısı: 3

array3'ün satır sayısı: 3

array2'ün sütun sayısı: 2


In [ ]:
# arrayler üzerinde indexleme ve slicing işlemleri
#array[start:end:step]
# start: Başlangıç indeksi (dahil). Eğer belirtilmezse, varsayılan değer 0'dır.
# end: Bitiş indeksi (hariç). Bu indeks dahil edilmez. Eğer belirtilmezse, dizinin sonuna kadar gider.
# step: Adım sayısı
array2 = [
    [1,2,3],
    [4,5,6]
    ]

print(array2[0])  # array2 nin ilk boyutunu yazdırır
print(array2[1])  # array2 nin ikinci boyutunu yazdırır

print("////")

print(array2[1][0]) #array2 nin ikinci boyutundaki ilk elemanı yazdırır yani 4
print(array2[0][2]) # array2 nin ilk boyutundaki 3. elemanı yazdırır yani 3

print("****")
print(array2[:]) #array2nin tamamını alır

print("---")
print(array2[0:1]) #boyutların indexine göre 0.indexten 1. indexe kadar alır
# yani sadece 1 2 3
print("****")

print(array2[1:2]) # 1.indexten 2.indexe kadar alır, 2. index dahil değil 4 5 6

[1, 2, 3]
[4, 5, 6]
////
4
3
****
[[1, 2, 3], [4, 5, 6]]
---
[[1, 2, 3]]
****
[[4, 5, 6]]


In [ ]:
print(array3[1:3]) #1. indexten 3. indexe kadar ama 3. index yok 1 ve 2yi alır

print("---")

print(array3[0]) # sadece 1. indexi alır

print("---")

print(array3[0][0]) # 0. indexin 0. elemanı yani ilk köşeli parantezn içindeki
 #ilk köşeli parantesi alır

[[[30 40]]

 [[50 60]]]
---
[[10 20]]
---
[10 20]


In [ ]:
"""3.Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur.
Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır """


import numpy as np

array4 = np.array([1, 2, 3, 4, 5])

array5 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

array6 = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])

print(array4)
print("***")
print(array5)
print("***")
print(array6)



[1 2 3 4 5]
***
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
***
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(array4[0])  #dizinin ilk elemanı
print(array4[1])  #dizinin 2. elemanı

print("---")

print(array5[1][0]) #dizinin 1. indexindeki 0. elemanı yazdırır 5
print(array5[2][2]) #dizinin 2. indexindeki 2. elemanı yazdırır 11

print("---")

print(array5[:]) #dizinin tamamını alır

print("---")
print(array6[0:1]) #0. indexten 1. indexe kadar(sadece 1. index)
print("---")
print(array6[1:2]) # 1.indexten 2.indexe kadar alır, 2. index dahil değil 4 5 6


1
2
---
5
11
---
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---
[[[1 2 3]
  [4 5 6]]]
---
[[[ 7  8  9]
  [10 11 12]]]


In [ ]:
"""4.Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur.
Bu arrayler satır ve sütun bazında birleştirilir. """

# 3 satır ve 4 sütundan oluşan sıfır matris
zero_matris = np.zeros((3, 4))
print(zero_matris)
print("Sıfır matris boyutu:", zero_matris.ndim) #ndim komutuyla np'de boyut alınır

print("***")
one_matris= np.ones((3, 4))
print("Bir matris boyutu:", one_matris.ndim)
print(one_matris)

print("***")

# Satır bazında birleştirme
one_zero_satir= np.concatenate((zero_matris, one_matris), axis=0)
# axis=0 olması dizilerin satırlarının üzerinde işlem yapılmasını sağlar
# burada alt alta satırlar birleştirildi

print("Satır Bazında Birleşmiş Matris:", one_zero_satir)
print("***")

# Sütun bazında birleştirme
one_zero_sutun = np.concatenate((zero_matris, one_matris), axis=1)
# axis=1 olması dizilerin sütunlarının üzerinde işlem yapılmasını sağlar
# burada yan yana sütunlar birleştirildi

print("Sütun Bazında Birleşmiş Matris:", one_zero_sutun)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Sıfır matris boyutu: 2
***
Bir matris boyutu: 2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
***
Satır Bazında Birleşmiş Matris: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
***
Sütun Bazında Birleşmiş Matris: [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]
